CREATE TABLE BOOKS (id int GENERATED BY DEFAULT AS IDENTITY primary key,
isbn character varying (20), title text, publisher text, price numeric,
year_of_publishing int, subject text, book_image_name text, available text,
available_copies int, description text, authors text,
added_date date, format character varying (10), avg_rating decimal(2,1));

CREATE TABLE CARTS(id int GENERATED BY DEFAULT AS IDENTITY primary key, total numeric,
subtotal numeric, quantity int);

CREATE TABLE WISHLISTS(id int GENERATED BY DEFAULT AS IDENTITY primary key);

CREATE TABLE CHECKOUTS(id int GENERATED BY DEFAULT AS IDENTITY primary key,
first_name character varying (20), last_name character varying (20), zip character varying (10),
address text, exp_date character varying (7), card_number character varying (20));

CREATE TABLE CARTS_ITEMS(id int GENERATED BY DEFAULT AS IDENTITY primary key,
total numeric, cart_id int, book_id int, quantity int,
FOREIGN KEY(cart_id) REFERENCES CARTS(id), FOREIGN KEY (book_id) REFERENCES BOOKS(id));


CREATE TABLE USERS (id int GENERATED BY DEFAULT AS IDENTITY primary key,
email character varying (30), username character varying (30), user_password text,
is_admin boolean, cart_id int, checkout_id int, wishlist_id int, accepted boolean, token text,
FOREIGN KEY(cart_id) REFERENCES CARTS(id), FOREIGN KEY(checkout_id) REFERENCES CHECKOUTS(id),
FOREIGN KEY(wishlist_id) REFERENCES WISHLISTS(id));