CREATE TABLE BOOKS (id int GENERATED BY DEFAULT AS IDENTITY primary key,
isbn character varying (20), title text, publisher text, price numeric,
year_of_publishing int, subject text, book_image_name text, available text,
available_copies int, description text, authors text,
added_date date, format character varying (10), avg_rating decimal(2,1));

CREATE TABLE CATEGORIES(id int GENERATED BY DEFAULT AS IDENTITY, category text);

CREATE TABLE CARTS(id int GENERATED BY DEFAULT AS IDENTITY primary key, total numeric,
subtotal numeric, quantity int);

CREATE TABLE WISHLISTS(id int GENERATED BY DEFAULT AS IDENTITY primary key);

CREATE TABLE BOOKS_WISHLISTS (book_id int, wishlist_id int, PRIMARY KEY(book_id, wishlist_id),
                                CONSTRAINT fk_book FOREIGN KEY(book_id) REFERENCES BOOKS(id),
                                CONSTRAINT fk_wishlist FOREIGN KEY(wishlist_id) REFERENCES WISHLISTS(id));

CREATE TABLE BOOKS_CATEGORIES(book_id int, category_id int, PRIMARY KEY(book_id, category_id),
                             CONSTRAINT fk_book FOREIGN KEY(book_id) REFERENCES BOOKS(id),
                             CONSTRAINT fk_category FOREIGN KEY(category_id) REFERENCES CATEGORIES(id));


CREATE TABLE CHECKOUTS(id int GENERATED BY DEFAULT AS IDENTITY primary key,
first_name character varying (20), last_name character varying (20), zip character varying (10),
address text, exp_date character varying (7), card_number character varying (20));

CREATE TABLE CARTS_ITEMS(id int GENERATED BY DEFAULT AS IDENTITY primary key,
total numeric, cart_id int, book_id int, quantity int,
FOREIGN KEY(cart_id) REFERENCES CARTS(id), FOREIGN KEY (book_id) REFERENCES BOOKS(id));

CREATE TABLE USERS (id int GENERATED BY DEFAULT AS IDENTITY primary key,
email character varying (30), username character varying (30), user_password text,
is_admin boolean, cart_id int, checkout_id int, wishlist_id int, accepted boolean, token text,
FOREIGN KEY(cart_id) REFERENCES CARTS(id), FOREIGN KEY(checkout_id) REFERENCES CHECKOUTS(id),
FOREIGN KEY(wishlist_id) REFERENCES WISHLISTS(id));

CREATE TABLE USERS_SESSIONS(id int GENERATED BY DEFAULT AS IDENTITY primary key,
session_id text, user_id int, FOREIGN KEY(user_id) REFERENCES USERS(id));

CREATE TABLE ORDERS_DETAILS(id int GENERATED BY DEFAULT AS IDENTITY primary key, address text,
                            zip character varying (12), first_delivery_date character varying (14),
                            last_delivery_date character varying (14),
                            delivery_interval character varying (30));

CREATE TABLE ORDERS(id int GENERATED BY DEFAULT AS IDENTITY primary key,
                    order_date character varying(12), title text, quantity int,
                    status text, total numeric, book_image_name text,
                    price int, user_id int, details_id int,
                    FOREIGN KEY(user_id) REFERENCES USERS(id),
                    FOREIGN KEY(details_id) REFERENCES ORDERS_DETAILS(id) ON DELETE CASCADE);

CREATE TABLE BOOKS_REVIEWS (id int GENERATED BY DEFAULT AS IDENTITY primary key,
                           review text, book_rating int, book_id int, user_id int,
                           FOREIGN KEY(book_id) REFERENCES BOOKS(id),
                           FOREIGN KEY(user_id) REFERENCES USERS(id));

